# docker-compose.yml
# Template Docker Compose untuk Aplikasi Laravel dengan FrankenPHP

version: '3.8'

services:
    # 1. Service Aplikasi Laravel dengan FrankenPHP
    app:
        build:
            context: .             # Konteks build adalah direktori saat ini
            dockerfile: Dockerfile.app # Menggunakan Dockerfile kustom untuk aplikasi
        container_name: ${APP_NAME}_app # Nama kontainer: codeflix_app (dari .env)
        volumes:
            - .:/var/www/html      # Mounting kode proyekmu ke dalam kontainer
            # Pastikan folder storage dan bootstrap/cache writable dari dalam kontainer
            # Ini krusial untuk FrankenPHP juga
            # - ./storage:/var/www/html/storage
            # - ./bootstrap/cache:/var/www/html/bootstrap/cache
        ports:
            - "${APP_PORT:-80}:80" # Map port host ke port 80 kontainer, default 80
            # FrankenPHP secara default mendengarkan di port 80/443
        environment:
            # Variabel lingkungan untuk aplikasi Laravel dari file .env host
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_KEY: ${APP_KEY}
            APP_DEBUG: ${APP_DEBUG}
            APP_URL: ${APP_URL}

            # Konfigurasi Database untuk kontainer 'app'
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: mysql           # Menunjuk ke service 'mysql' di bawah
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

            # Variabel lingkungan khusus FrankenPHP (opsional, untuk konfigurasi lebih lanjut)
            # SERVER_NAME: ${APP_URL} # Domain yang akan dilayani Caddy
            # PHP_MEMORY_LIMIT: 256M
            # PHP_MAX_INPUT_TIME: 120
            # PHP_POST_MAX_SIZE: 100M

        depends_on:
            - mysql                # Aplikasi tergantung pada database MySQL
        restart: unless-stopped  # Kontainer akan otomatis restart kecuali dihentikan manual

    # 2. Service MySQL (Database) - Sama seperti sebelumnya
    mysql:
        image: mysql:8.0          # Menggunakan MySQL versi 8.0 (bisa diubah ke 5.7 dll.)
        container_name: ${APP_NAME}_mysql # Nama kontainer: codeflix_mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Password root database (bisa sama dengan DB_PASSWORD)
            MYSQL_DATABASE: ${DB_DATABASE}      # Database yang akan dibuat secara otomatis
            MYSQL_USER: ${DB_USERNAME}          # User database
            MYSQL_PASSWORD: ${DB_PASSWORD}      # Password user database
        ports:
            - "${DB_PORT:-3306}:3306" # Map port 3306 host ke port 3306 kontainer, default 3306
        volumes:
            - mysql_data:/var/lib/mysql # Data database akan disimpan di named volume agar persisten
        restart: unless-stopped

# Named volumes untuk menyimpan data database secara persisten
volumes:
    mysql_data:
        driver: local
